# Generated by Django 5.2.5 on 2025-09-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.IntegerField(help_text='Price in whole currency units (e.g. IDR)')),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(help_text='Image URL of the product')),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('boots', 'Boots'), ('ball', 'Ball'), ('accessory', 'Accessory'), ('training', 'Training Gear')], max_length=30)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
